import { createHash, createHmac } from 'node:crypto';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { env } from '@/lib/env';
import { NotFoundError } from '@/lib/errors';
import type { PutObjectInput, PutObjectResult, StorageProvider, StoredObject } from './types';

/**
 * Filesystem storage for local development and for running the CRM before AWS
 * is provisioned. Signed URLs are HMAC-signed links to an authenticated route,
 * so behaviour matches S3 closely enough that swapping providers is a config
 * change, not a code change.
 *
 * Not intended for production: no redundancy, no encryption at rest.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';
  private root: string;

  constructor() {
    this.root = resolve(process.cwd(), env.LOCAL_STORAGE_DIR);
  }

  private pathFor(key: string): string {
    // Reject traversal — keys are generated by us, but never trust them.
    if (key.includes('..')) throw new Error('Invalid storage key');
    return join(this.root, key);
  }

  async put(input: PutObjectInput): Promise<PutObjectResult> {
    const body = Buffer.isBuffer(input.body) ? input.body : Buffer.from(input.body);
    const path = this.pathFor(input.key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    await writeFile(
      `${path}.meta.json`,
      JSON.stringify({ contentType: input.contentType, metadata: input.metadata ?? {} }),
    );
    return {
      key: input.key,
      sizeBytes: body.length,
      sha256: createHash('sha256').update(body).digest('hex'),
    };
  }

  async get(key: string): Promise<StoredObject> {
    const path = this.pathFor(key);
    try {
      const body = await readFile(path);
      let contentType = 'application/octet-stream';
      try {
        const meta = JSON.parse(await readFile(`${path}.meta.json`, 'utf8'));
        contentType = meta.contentType ?? contentType;
      } catch {
        /* metadata is best-effort */
      }
      return { key, body, contentType, sizeBytes: body.length };
    } catch {
      throw new NotFoundError('Document');
    }
  }

  async delete(key: string): Promise<void> {
    const path = this.pathFor(key);
    await rm(path, { force: true });
    await rm(`${path}.meta.json`, { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  async getSignedUrl(
    key: string,
    opts: { ttlSeconds?: number; downloadFilename?: string } = {},
  ): Promise<string> {
    const expires = Math.floor(Date.now() / 1000) + (opts.ttlSeconds ?? env.S3_SIGNED_URL_TTL);
    const signature = signLocalKey(key, expires);
    const params = new URLSearchParams({ key, expires: String(expires), signature });
    if (opts.downloadFilename) params.set('filename', opts.downloadFilename);
    return `${env.APP_URL}/api/storage/local?${params.toString()}`;
  }
}

export function signLocalKey(key: string, expires: number): string {
  return createHmac('sha256', env.NEXTAUTH_SECRET).update(`${key}:${expires}`).digest('hex');
}

export function verifyLocalSignature(key: string, expires: number, signature: string): boolean {
  if (!Number.isFinite(expires) || expires * 1000 < Date.now()) return false;
  const expected = signLocalKey(key, expires);
  // Length check first so timingSafeEqual never throws.
  return expected.length === signature.length && expected === signature;
}
